# Generated by Django 5.1.1 on 2025-09-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, help_text='Section (e.g., A, B, C)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, help_text='Year of study (e.g., 1st Year, 2nd Year, 3rd Year, 4th Year)', max_length=20, null=True),
        ),
    ]
