# Generated by Django 5.2.8 on 2025-11-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_section_user_year_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="important",
            field=models.BooleanField(
                default=False, help_text="Mark notification as important"
            ),
        ),
    ]
