# Generated by Django 5.2.8 on 2025-11-17 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_club_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles': 'FACULTY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='coordinated_clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
