# Generated by Django 5.2.7 on 2026-02-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_club_advisor_alter_club_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='certificate_template',
            field=models.CharField(choices=[('sample.jpg', 'Default Template'), ('tech_club.jpg', 'Tech Club Template'), ('sports_club.jpg', 'Sports Club Template'), ('cultural_club.jpg', 'Cultural Club Template'), ('science_club.jpg', 'Science Club Template')], default='sample.jpg', help_text='Certificate template for this club', max_length=100),
        ),
    ]
