# Generated by Django 5.2.7 on 2026-02-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_club_certificate_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='certificate_template',
            field=models.ImageField(blank=True, help_text='Upload a certificate template image (JPG/PNG, recommended: 1500x1000px)', null=True, upload_to='certificate_templates/'),
        ),
    ]
