# Generated by Django 5.2.8 on 2025-11-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0002_attendancesession_alter_attendance_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="ref_code",
            # Initially allow NULL and no unique constraint so the migration can run
            # and we can backfill values in a separate data migration.
            field=models.CharField(blank=True, null=True, max_length=32, unique=False),
        ),
    ]
