# Generated by Django 5.2.8 on 2025-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_make_ref_code_nonnull_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="ref_code",
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
