# Generated by Django 5.2.8 on 2025-11-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_attendance_ref_code"),
        ("attendance", "0006_normalize_ref_code"),
    ]

    operations = []
