# Generated by Django 5.2.6 on 2025-09-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("CLUB_EVENT", "Club Event"),
                            ("DEPARTMENT_EVENT", "Department Event"),
                            ("NATIONAL_DAY", "National Day/Week"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_time", models.DateTimeField()),
                (
                    "visible_to",
                    models.CharField(
                        default="all",
                        help_text="Visibility: all, club, department, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_entries",
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
