# Generated by Django 5.2.8 on 2025-11-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventassociation_eventcollaboration"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventcollaboration",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="eventcollaboration",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="eventcollaboration",
            name="club",
        ),
        migrations.RemoveField(
            model_name="eventcollaboration",
            name="department",
        ),
        migrations.RemoveField(
            model_name="eventcollaboration",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventcollaboration",
            name="requested_by",
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="student",
        ),
        migrations.DeleteModel(
            name="EventAssociation",
        ),
        migrations.DeleteModel(
            name="EventCollaboration",
        ),
        migrations.DeleteModel(
            name="EventRegistration",
        ),
    ]
