# Generated by Django 5.2.8 on 2025-11-16 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_eventcollaboration_unique_together_and_more"),
        ("users", "0003_user_section_user_year_of_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.ForeignKey(
                blank=True,
                help_text="Club associated with this event (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="users.club",
            ),
        ),
    ]
