# Generated by Django 5.2.8 on 2025-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_eventregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
